# Generated by Django 4.0.1 on 2022-02-04 10:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import projects.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.CharField(default=projects.models.idgen, max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('cDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('size', models.IntegerField(default=25)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='projectAccounts',
            fields=[
                ('id', models.CharField(default=projects.models.idgen, max_length=20, primary_key=True, serialize=False)),
                ('visiblity', models.BooleanField(default=True)),
                ('account', models.ForeignKey(default=projects.models.idgen, on_delete=django.db.models.deletion.CASCADE, to='accounts.instaaccounts')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
    ]
