# Generated by Django 4.0.1 on 2022-01-30 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='projectAccounts',
            fields=[
                ('username', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('visiblity', models.BooleanField(default=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
    ]
