# Generated by Django 4.0.1 on 2022-02-05 04:00

import accounts.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instaaccounts',
            old_name='media',
            new_name='medias',
        ),
        migrations.CreateModel(
            name='media',
            fields=[
                ('mediaId', models.CharField(default=accounts.models.idgen, max_length=20, primary_key=True, serialize=False)),
                ('isVideo', models.BooleanField(default=False)),
                ('isPhoto', models.BooleanField(default=False)),
                ('likes', models.CharField(default='', max_length=20)),
                ('comments', models.CharField(default='', max_length=20)),
                ('views', models.CharField(default='', max_length=20)),
                ('likeIn', models.JSONField(default=dict)),
                ('commentsIn', models.JSONField(default=dict)),
                ('viewsIn', models.JSONField(default=dict)),
                ('Date', models.DateTimeField(default=datetime.datetime.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.instaaccounts')),
            ],
        ),
    ]
