# Generated by Django 4.0.1 on 2022-02-05 04:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_media_instaaccounts_medias_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='Date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
