# Generated by Django 4.0.1 on 2022-02-06 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_media_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='isMultiple',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='media',
            name='multiItems',
            field=models.JSONField(default=dict),
        ),
    ]
