# Generated by Django 4.0.1 on 2022-02-10 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_media_ismultiple_media_multiitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='instaaccounts',
            name='comments',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='instaaccounts',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='instaaccounts',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
