# Generated by Django 4.0.1 on 2022-02-17 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_media_comments_alter_media_likes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='dataIn',
            field=models.JSONField(default=dict),
        ),
    ]
