# Generated by Django 4.0.1 on 2022-02-17 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_media_datain'),
    ]

    operations = [
        migrations.AddField(
            model_name='instaaccounts',
            name='dataIn',
            field=models.JSONField(default=dict),
        ),
    ]
