# Generated by Django 4.0.1 on 2022-02-18 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_instaaccounts_datain'),
    ]

    operations = [
        migrations.AddField(
            model_name='instaaccounts',
            name='hashtags',
            field=models.TextField(default=' '),
        ),
        migrations.AddField(
            model_name='media',
            name='hashtags',
            field=models.TextField(default=' '),
        ),
    ]
