# Generated by Django 4.0.1 on 2022-02-18 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_instaaccounts_hashtags_media_hashtags'),
    ]

    operations = [
        migrations.AddField(
            model_name='instaaccounts',
            name='bio',
            field=models.TextField(default=' '),
        ),
        migrations.AddField(
            model_name='media',
            name='caption',
            field=models.TextField(default=' '),
        ),
    ]
