# Generated by Django 4.0.1 on 2022-02-18 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_instaaccounts_bio_media_caption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='comments',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='media',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='media',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
